# Application
DEVELOPMENT_ENVIRONMENT = 'development'
STATIC_ASSET_HASH_LENGTH = 12

# Authentication and sessions
COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 365 * 5
COOKIE_NAME = 'geosquare_session'
CSRF_COOKIE_NAME = 'geosquare_csrf'
CSRF_SALT = 'geosquare-csrf'
LASTLOGIN_PROVIDER = 'lastlogin'
PRODUCTION_ORIGIN = 'https://geosquare.app'

# Logging
SLOW_EVENT_THRESHOLD_MILLISECONDS = 1000

# External services
FEEDBACK_REQUEST_TIMEOUT_SECONDS = 30
GITHUB_API_VERSION = '2022-11-28'
GITHUB_REQUEST_TIMEOUT_SECONDS = 30
GITHUB_WORKFLOW_REF = 'main'
RESEND_API_URL = 'https://api.resend.com/emails'

# Database
PRODUCTION_DATABASE_NAME = 'GeoSquare'

# Game
GAME_ROUND_COUNT = 5

# Profiles
HISTORY_PAGE_SIZE = 20

# Side missions
NAME_CHAIN_MINIMUM_STEP_POPULATION = 150_000
SIDE_MISSION_TARGET_COUNT = 3

# Matching
ADDITIONAL_UNMATCHED_TRAILING_TOKEN_PENALTY = 15.0
AUTO_ACCEPT_SCORE = 95.0
FUZZY_ALTERNATE_NAME_PENALTY = 7.5
FUZZY_LINE_SCORE = 88.5
NAME_DESCRIPTOR_WEIGHT = 0.5
NEARBY_FIRST_RING_PENALTY = 15.0
NEARBY_NOTORIETY_SCALE = 10.0
NEARBY_RING_PENALTY_DECAY = 5.0
PHONETIC_TOKEN_SCORE = 92.0
UNMATCHED_INPUT_TOKEN_PENALTY = 30.0
UNMATCHED_INTERIOR_TOKEN_PENALTY = 20.0
UNMATCHED_LEADING_TOKEN_PENALTY = 30.0
UNMATCHED_TRAILING_TOKEN_PENALTY = 5.0

# Square pool generation
POOL_GAME_LOW_PLAYABILITY_SCORE = 80.0
POOL_GAME_MAX_LOW_PLAYABILITY_ROUNDS = 1
POOL_GAME_REQUIRED_HIGH_PLAYABILITY_SCORE = 90.0
POOL_VIABILITY_MIN_PLAYABILITY_SCORE = 75.0
SAME_GAME_MIN_DISTANCE_SQUARES = 3.0
SQUARE_POOL_CITY_BUFFER_DEGREES = 0.25
SQUARE_POOL_MAX_LAT = 78.0
SQUARE_POOL_MAX_LON = 180.0
SQUARE_POOL_MIN_LAT = -56.0
SQUARE_POOL_MIN_LON = -180.0